const CartActionTypes = {
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CHANGE_QUANTITY_TO_CART: 'CHANGE_QUANTITY_TO_CART',
  SET_SHIPPING_METHOD: 'SET_SHIPPING_METHOD',
};
export default CartActionTypes;
