const AppActionTypes = {
  TOGGLE_HOME_MENU: 'TOGGLE_HOME_MENU',
  TOGGLE_CART_MENU: 'TOGGLE_CART_MENU',
  TOGGLE_SEARCH_MENU: 'TOGGLE_SEARCH_MENU',
  TOGGLE_CATEGORY_MENU: 'TOGGLE_CATEGORY_MENU',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  RESET_MENU: 'RESET_MENU',
};
export default AppActionTypes;
