const CategoryActionTypes = {
  FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  TOGGLE_CATEGORY_LOADER: 'TOGGLE_CATEGORY_LOADER',
};
export default CategoryActionTypes;
