export default {
  categories: {
    office: {
      name: 'Office',
      title: 'Premium Office furniture',
      description: `Finest products collected amongst the countrie's bestartisans.`,
      countProducts: 391,
      url: '/products',
      background: 'https://i.imgur.com/zIkWZR8.jpg',
      class: '',
      sizeContent: '',
    },
    for_kids: {
      name: 'For Kids',
      title: 'Premium Office furniture',
      description: `Finest products collected amongst the countrie's bestartisans.`,
      countProducts: 376,
      url: '/products',
      background: 'https://i.imgur.com/b4zFHkL.jpg',
      class: 'is-child has-min-height',
      sizeContent: '',
    },
    accesories: {
      name: 'Accesories',
      title: 'Premium Office furniture',
      description: `Finest products collected amongst the countrie's bestartisans.`,
      countProducts: 200,
      url: '/products',
      background: 'https://i.imgur.com/oYF0TNq.jpg',
      class: '',
      sizeContent: 'is-small',
    },
    kitchen: {
      name: 'Kitchen',
      title: 'Premium Office furniture',
      description: `Finest products collected amongst the countrie's bestartisans.`,
      countProducts: 87,
      url: '/products',
      background: 'https://i.imgur.com/cozurD7.jpg',
      class: '',
      sizeContent: 'is-small',
    },
    house: {
      name: 'House',
      title: 'Premium Office furniture',
      description: `Finest products collected amongst the countrie's bestartisans.`,
      countProducts: 32,
      url: '/products',
      background: 'https://i.imgur.com/0zBnZx4.jpg',
      class: 'has-min-height',
      sizeContent: '',
    },
  },
};
