export default [
  {
    name: 'Office',
    title: 'Premium Office furniture',
    description: `Finest products collected amongst the countrie's bestartisans.`,
    countProducts: 391,
    url: '/products',
    background: 'https://i.postimg.cc/63278DM5/zIkWZR8.jpg',
    class: '',
    sizeContent: '',
    slug: 'office',
  },
  {
    name: 'For Kids',
    title: 'Premium Office furniture',
    description: `Finest products collected amongst the countrie's bestartisans.`,
    countProducts: 376,
    url: '/products',
    background: 'https://i.postimg.cc/MTCnVdL0/b4zFHkL.jpg',
    class: 'is-child has-min-height',
    sizeContent: '',
    slug: 'for-kids',
  },
  {
    name: 'Accessories',
    title: 'Premium Office furniture',
    description: `Finest products collected amongst the countrie's bestartisans.`,
    countProducts: 200,
    url: '/products',
    background: 'https://i.postimg.cc/zvTVjTms/oYF0TNq.jpg',
    class: '',
    sizeContent: 'is-small',
    slug: 'accesories',
  },
  {
    name: 'Kitchen',
    title: 'Premium Office furniture',
    description: `Finest products collected amongst the countrie's bestartisans.`,
    countProducts: 87,
    url: '/products',
    background: 'https://i.postimg.cc/J7XDMCyp/cozurD7.jpg',
    class: '',
    sizeContent: 'is-small',
    slug: 'kitchen',
  },
  {
    name: 'House',
    title: 'Premium Office furniture',
    description: `Finest products collected amongst the countrie's bestartisans.`,
    countProducts: 32,
    url: '/products',
    background: 'https://i.postimg.cc/sDRB2H7s/0zBnZx4.jpg',
    class: 'has-min-height',
    sizeContent: '',
    slug: 'house',
  },
];
