const WishActionTypes = {
  CREATE_WISH_START: 'CREATE_WISH_START',
  CREATE_WISH_SUCCESS: 'CREATE_WISH_SUCCESS',
  CREATE_WISH_FAILURE: 'CREATE_WISH_FAILURE',
  FETCH_WISHES_START: 'FETCH_WISHES_START',
  FETCH_WISHES_SUCCESS: 'FETCH_WISHES_SUCCESS',
  FETCH_WISHES_FAILURE: 'FETCH_WISHES_FAILURE',
  DELETE_WISH_START: 'DELETE_WISH_START',
  DELETE_WISH_SUCCESS: 'DELETE_WISH_SUCCESS',
  DELETE_WISH_FAILURE: 'DELETE_WISH_FAILURE',
  DELETE_ITEM_TO_WISH_START: 'DELETE_ITEM_TO_WISH_START',
  DELETE_ITEM_TO_WISH_SUCCESS: 'DELETE_ITEM_TO_WISH_SUCCESS',
  DELETE_ITEM_TO_WISH_FAILURE: 'DELETE_ITEM_TO_WISH_FAILURE',
  ON_TOGGLE_WISH_MODAL: 'ON_TOGGLE_WISH_MODAL',
  ADD_ITEM_TO_WISH_START: 'ADD_ITEM_TO_WISH_START',
  ADD_ITEM_TO_WISH_SUCCESS: 'ADD_ITEM_TO_WISH_SUCCESS',
  ADD_ITEM_TO_WISH_FAILURE: 'ADD_ITEM_TO_WISH_FAILURE',
};
export default WishActionTypes;
